name: 'Gist Write Action'
description: 'The action to write content to a gist'
inputs:
  auth:
    description: 'Your secret with the gist scope'
    required: true
  gistID:
    description: 'Gist ID'
    required: true
  filename:
    description: 'Name of the file at the gist to write data at'
    required: true
  label:
    description: 'The left text of the badge'
    required: true
  message:
    description: 'The right text of the badge'
    required: true
  color:
    description: 'The right color of the badge'
    required: false
  namedLogo:
    description: 'A logo name from simpleicons.org'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'award'
  color: 'blue'
