name: Validate and Test Coverage Scripts on pull or push request
run-name: ${{ github.actor }} is testing ${{ github.repository }}
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run validate
      - run: |
          SUMMARY="$(npm run test -- --coverage --coverageReporters='text-summary' | tail -2 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
          REF=${{ github.ref }}
          echo "github.ref: $REF"
          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
      - if: ${{ env.COVERAGE && github.ref == 'refs/heads/main' }}
        name: Create the Badge
        uses: MadeleenRoestorff/coverage-gist-badge@main
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 37d283de48f9508f6aed66f51beff8db
          filename: coverage_gist_badge_${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          namedLogo: jest
        name: show incremented value "${{ steps.next.outputs.value }}"
        run: echo ${{ steps.next.outputs.value }}
